name: E2E Test Case 1 Register User

on:
  # Triggering on pull request to main branch
  pull_request:
    branches:
      - main
  # Triggering on a specific time (e.g., daily at midnight UTC)
  schedule:
    - cron: '0 0 * * */3'  # Every day at midnight UTC
    
  # Manually triggered workflow with inputs for browser, headless options, and pull request option
  workflow_dispatch:
    inputs:
      allureReportPath:
        description: 'Specify the Allure report path'
        required: false
        default: 'target/site/allure-maven-plugin/index.html'  # Default path if not provided
      triggerPR:
        description: 'Trigger workflow on pull request to main branch (true/false)'
        required: true
        default: 'false'  # Default to not trigger PR workflow

jobs:
  windows_edge:
    name: Windows Edge Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu' 
              java-version: '21'
  
        - name: Set up Maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.9.9
  
        - name: Build and test
          run: mvn -Dbrowser="edge" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test
  
        - name: Generate Allure Report
          continue-on-error: true
          run: mvn allure:report
    
        - name: Upload Allure Report
          uses: actions/upload-artifact@v3
          with:
            name: Allure Report ubento test
            path: target/site/allure-maven-plugin/index.html
            
        - name: Publish Report
          continue-on-error: true
          uses: dorny/test-reporter@v1
          if: success() || failure()
          with:
            name: Tests Report Headless_Ubuntu
            path: 'target/surefire-reports/TEST-*.xml'
            reporter: java-junit
            
  ubuntu_chrome:
    name: Ubuntu Chrome Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Install Chrome and ChromeDriver
          uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: 'latest'
            install-chromedriver: true
    
        - name: Install dependencies
          run: sudo apt-get install -y libnss3 libgconf-2-4
      
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu' 
              java-version: '21'
  
        - name: Set up Maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.9.9
  
        - name: Build and test
          run: mvn -Dbrowser="chrome" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test
  
        - name: Generate Allure Report
          continue-on-error: true
          run: mvn allure:report
          
        - name: Upload Allure Report
          uses: actions/upload-artifact@v3
          with:
            name: Allure Report ubento test
            path: ${{ github.event.inputs.allureReportPath }}
            
        - name: Publish Report
          continue-on-error: true
          uses: dorny/test-reporter@v1
          if: success() || failure()
          with:
            name: Tests Report Headless_Ubuntu
            path: ${{ github.event.inputs.allureReportPath }}
            reporter: java-junit
