name: E2E Test Case 1 Register User

on:
  # Triggering on pull request to main branch
  pull_request:
    branches:
      - main
  # Triggering on a specific time (e.g., daily at midnight UTC)
  schedule:
    - cron: '0 0 * * */3'  # Every day at midnight UTC
    
  # Manually triggered workflow with inputs for browser, headless options, and pull request option
  workflow_dispatch:
    inputs:
      headless:
        description: 'Run in headless mode (true/false)'
        required: true
        default: 'true'
      allureReportPath:
        description: 'Specify the Allure report path'
        required: false
        default: 'target/allure-report'  # Default path if not provided
      triggerPR:
        description: 'Trigger workflow on pull request to main branch (true/false)'
        required: true
        default: 'false'  # Default to not trigger PR workflow

jobs:
  windows_edge:
    name: Windows Edge Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu' 
              java-version: '21'
  
        - name: Set up Maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.9.9
  
        - name: Build and test
          run: mvn -Dbrowser="edge" -Dtest="automationexercise.tests.UserRegistrationTest" test
  
        - name: Generate Allure Report
          run: mvn allure:report
          env:
              HEADLESS: ${{ github.event.inputs.headless }}
    
        - name: Upload Allure report as artifact
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: ${{ github.event.inputs.allureReportPath }}

  ubuntu_chrome:
    name: Ubuntu Chrome Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Install Chrome
          run: sudo apt-get install -y google-chrome-stable
    
        - name: Set up ChromeDriver
          uses: actions/setup-chromedriver@v1
          with:
            version: 'latest'
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu' 
              java-version: '21'
  
        - name: Set up Maven
          uses: stCarolas/setup-maven@v5
          with:
            maven-version: 3.9.9
  
        - name: Build and test
          run: mvn -Dbrowser="chrome" -Dtest="automationexercise.tests.UserRegistrationTest" test
  
        - name: Generate Allure Report
          run: mvn allure:report
          env:
              HEADLESS: ${{ github.event.inputs.headless }}
    
        - name: Upload Allure report as artifact
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: ${{ github.event.inputs.allureReportPath }}
