name: E2E Test Case 1 Register User

permissions:
  contents: write  # Grants write access to contents
  actions: write   # Ensures actions can upload artifacts

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '* */2 * * *'
  workflow_dispatch:
    inputs:
      allureReportPath:
        description: 'Specify the Allure report path'
        required: false
        default: 'target/site/allure-maven-plugin/index.html'
      triggerPR:
        description: 'Trigger workflow on pull request to main branch (true/false)'
        required: true
        default: 'false'

jobs:
  windows_edge:
    name: Windows Edge Test
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: windows-latest
    permissions:
      contents: write  # Grants write access to contents
      actions: write   # Ensures actions can upload artifacts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="edge" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Windows Test
          path: ${{ github.event.inputs.allureReportPath }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              target/surefire-reports/TEST-*.xml

  ubuntu_chrome:
    name: Ubuntu Chrome Test
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Grants write access to contents
      actions: write   # Ensures actions can upload artifacts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="chrome" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Windows Test
          path: ${{ github.event.inputs.allureReportPath }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              target/surefire-reports/TEST-*.xml
