name: E2E Test Case 1 Register User

permissions:
  contents: write  # Grants write access to contents
  actions: write   # Required for uploading artifacts

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '* */2 * * *'
  workflow_dispatch:
    inputs:
      allureReportPath:
        description: 'Specify the Allure report path'
        required: false
        default: 'target/site/allure-maven-plugin'
      triggerPR:
        description: 'Trigger workflow on pull request to main branch (true/false)'
        required: true
        default: 'false'

jobs:
  windows_edge:
    name: Windows Edge Test
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="edge" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Windows Test
          path: ${{ github.event.inputs.allureReportPath }}

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Headless Windows Edge
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  ubuntu_chrome:
    name: Ubuntu Chrome Test
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="chrome" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test

      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Ubuntu Test
          path: ${{ github.event.inputs.allureReportPath }}

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Headless Ubuntu Chrome
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
