name: E2E Test Case 1 Register User

on:
  schedule:
    - cron: '0 */6 * * *' 

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
   inputs:
     testsPath:
       description: 'Path to Tests to be Executed'
       default: 'automationexercise.tests.UserRegistrationTest'
     triggerPR:
      description: 'Trigger workflow on pull request to main branch (true/false)'
      required: true
      default: 'false'  # Default to not trigger PR workflow

jobs:
  E2E_Ubuntu_Chrome_Test:
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Execute Ububtu Chrome Tests
        continue-on-error: true
        run: mvn test -Dbrowser="chrome" -Dheadless="true" -Dtest="${{ github.event.inputs.testsPath }}"

      - name: Generate Allure Report Single File 
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu Chrome Tests Allure Report
          path: target/site/allure-maven-plugin/index.html

      - name: Publish Ubuntu Chrome Tests Allure Report Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/TEST-*.xml
            
  E2E_Windows_Edge_Tests:
    if: ${{ github.event.inputs.triggerPR == 'true' }}  
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.9

      - name: Execute Windows Edge Tests
        continue-on-error: true
        run: mvn test -Dbrowser="edge" -Dheadless="false" -Dtest="${{ github.event.inputs.testsPath }}"

      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Edge Tests Allure Report
          path: target/site/allure-maven-plugin/index.html


      - name: Publish Windows Edge Tests Allure Report Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            target/surefire-reports/TEST-*.xml
