name: E2E Test Case 1 Register User

permissions:
  contents: write

on:
  # Triggering on pull request to main branch
  pull_request:
    branches:
      - main
  schedule:
    - cron: '* */2 * * *'

  workflow_dispatch:
    inputs:
      triggerPR:
        description: 'Trigger workflow on pull request to main branch (true/false)'
        required: true
        default: 'false'

jobs:
  windows_edge:
    name: Windows Edge Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="edge" -Dheadless="true" -Dtest="automationexercise.tests.UserRegistrationTest" test

      - name: List Allure Report Directory Contents
        run: Get-ChildItem -Recurse target/site/allure-maven-plugin

      - name: Publish Allure Report with History
        uses: simple-elf/allure-report-with-history@main
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: target/site/allure-maven-plugin
          allure_history: target/site/allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu_chrome:
    name: Ubuntu Chrome Test
    # If triggerPR is true, this job will run
    if: ${{ github.event.inputs.triggerPR == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Build and test
        run: mvn -Dbrowser="chrome" -Dheadless="true" -Dtest="a
